server:
  port: ${PORT:0}

spring:

  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/initest  
    driver-class-name: oracle.jdbc.OracleDriver  
    username: bige_min  
    password: Bige_2018  
  
  h2:
    console:
      enabled: false
      path: /h2-console

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        '[show_sql]': true
        '[use_sql_comments]': false
        '[format_sql]': false
        '[event.merge.entity_copy_observer]': allow
    show-sql: true
  sql:
    init:
      mode: always
      platform: sql

configuration:
    texto: Configurando entorno Desarrollo ...
    autor:
        nombre: Francisco Yujra
        email: francisco.yujra@geoenergia.gob.ec
