server:
  port: ${PORT:0}

spring:
      
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/initest  
    driver-class-name: oracle.jdbc.OracleDriver  
    username: bige_lab  
    password: Bige_2018  
  
  h2:
    console:
      enabled: false
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        '[show_sql]': true
        '[use_sql_comments]': false
        '[format_sql]': false
        '[event.merge.entity_copy_observer]': allow
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  client:
    enabled: true

  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}